{% set name = "spcqe" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spcqe-{{ version }}.tar.gz
  sha256: 063c3f9b9325e37ed0407cfc3a3b5d7ad90878d183479f88757b78d77e363601

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - cvxpy
    - scikit-learn
    - tqdm
    - pybind11
    - sig-decomp

test:
  imports:
    - spcqe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/spcqe/
  summary: Smooth periodic consistent quantile estimation
  dev_url: https://github.com/cvxgrp/spcqe/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pluflou
